title: Saurav's page
name: "Homepage of Saurav Shekhar"
email: sauravshekhar01@gmail.com
logo: /assets/img/leaf.jpg
home: /index
description: >
  Things I find interesting.
twitter_username: saurav_shekhar
github_username:  sshekh
mathjax: true
show_home: true
google_analytics:
theme: jekyll-theme-minimal
